name: test
on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java_version: [
          11,
          17,
          21
        ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Scala
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ matrix.java_version }}
          cache: sbt
      - name: Format
        run: sbt scalafmtAll sample/scalafmtAll scalafmtSbt
      - name: Test and coverage
        run: sbt clean sample/compile coverage +test; sbt coverageReport
      - name: Archive coverage
        uses: actions/upload-artifact@v3
        with:
          name: scoverage-report
          path: target/scala-2.13/scoverage-report
